### PR TITLE
Fix encoding nil values for CustomEncoder. Fixes #35.

### LINKED ISSUE #35: More custom encoding issues
https://github.com/dim/msgpack/tree/bug/custom-coders

```
--- FAIL: TestBin (0.00s)
panic: reflect: call of reflect.Value.IsNil on struct Value [recovered]
  panic: reflect: call of reflect.Value.IsNil on struct Value

goroutine 62 [running]:
testing.func·006()
  $GOROOT/src/testing/testing.go:441 +0x181
reflect.Value.IsNil(0xa0fea0, 0xc20802b070, 0xd9, 0x8abd00)
  $GOROOT/src/reflect/value.go:942 +0x100
gopkg.in/vmihailenco/msgpack%2ev2.encodeCustomValue(0xc208087e90, 0xa0fea0, 0xc20802b070, 0xd9, 0x0, 0x0)
  $GOPATH/src/gopkg.in/vmihailenco/msgpack.v2/typeinfo.go:240 +0x4e
gopkg.in/vmihailenco/msgpack%2ev2.(*Encoder).EncodeValue(0xc208087e90, 0xa0fea0, 0xc20802b070, 0xd9, 0x0, 0x0)
  $GOPATH/src/gopkg.in/vmihailenco/msgpack.v2/encode.go:119 +0xa1
gopkg.in/vmihailenco/msgpack%2ev2.(*Encoder).encodeArray(0xc208087e90, 0x890f40, 0xc20800b360, 0x57, 0x0, 0x0)
  $GOPATH/src/gopkg.in/vmihailenco/msgpack.v2/slice.go:114 +0x135
gopkg.in/vmihailenco/msgpack%2ev2.(*Encoder).encodeSlice(0xc208087e90, 0x890f40, 0xc20800b360, 0x57, 0x0, 0x0)
  $GOPATH/src/gopkg.in/vmihailenco/msgpack.v2/slice.go:105 +0xa6
gopkg.in/vmihailenco/msgpack%2ev2.encodeSliceValue(0xc208087e90, 0x890f40, 0xc20800b360, 0x57, 0x0, 0x0)
  $GOPATH/src/gopkg.in/vmihailenco/msgpack.v2/typeinfo.go:164 +0x58
gopkg.in/vmihailenco/msgpack%2ev2.(*Encoder).EncodeValue(0xc208087e90, 0x890f40, 0xc20800b360, 0x57, 0x0, 0x0)
  $GOPATH/src/gopkg.in/vmihailenco/msgpack.v2/encode.go:119 +0xa1
gopkg.in/vmihailenco/msgpack%2ev2.(*Encoder).encode(0xc208087e90, 0x890f40, 0xc20800b360, 0x0, 0x0)
  $GOPATH/src/gopkg.in/vmihailenco/msgpack.v2/encode.go:114 +0x3d9
gopkg.in/vmihailenco/msgpack%2ev2.(*Encoder).Encode(0xc208087e90, 0xc208143e78, 0x1, 0x1, 0x0, 0x0)
  $GOPATH/src/gopkg.in/vmihailenco/msgpack.v2/encode.go:67 +0xc6
gopkg.in/vmihailenco/msgpack%2ev2.Marshal(0xc208143e78, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
  $GOPATH/src/gopkg.in/vmihailenco/msgpack.v2/encode.go:45 +0x320
gopkg.in/vmihailenco/msgpack%2ev2_test.TestBin(0xc208068240)
  $GOPATH/src/gopkg.in/vmihailenco/msgpack.v2/types_test.go:132 +0x140
testing.tRunner(0xc208068240, 0xdf1fa8)
  $GOROOT/src/testing/testing.go:447 +0xbf
created by testing.RunTests
  $GOROOT/src/testing/testing.go:555 +0xa8b
```

### PR DESCRIPTION
**Pull request by vmihailenco**

### CODE REVIEW

File: typeinfo.go [hunk 1]
```diff
@@ -237,7 +237,7 @@ func decodeStructValue(d *Decoder, v reflect.Value) error {
 //------------------------------------------------------------------------------
 
 func encodeCustomValue(e *Encoder, v reflect.Value) error {
-	if v.IsNil() {
+	if v.Kind() == reflect.Ptr && v.IsNil() {
```
Comment (vmihailenco) [inline typeinfo.go]: Most likely this should be extended for array and slice too, but I don't want to do it without test...

Comment (vmihailenco) [inline typeinfo.go]: "IsNil reports whether its argument v is nil. The argument must be a chan, func, interface, map, pointer, or slice value; if it is not, IsNil panics."

Will do a proper fix tomorrow.
